//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.BLL.PegasoGlobal {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD")]
    public partial class WCFServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionNameField;
        
        private string faultIdField;
        
        private string faultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ExceptionName {
            get {
                return this.exceptionNameField;
            }
            set {
                this.exceptionNameField = value;
                this.RaisePropertyChanged("ExceptionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FaultId {
            get {
                return this.faultIdField;
            }
            set {
                this.faultIdField = value;
                this.RaisePropertyChanged("FaultId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string FaultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("FaultMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", ConfigurationName="PegasoGlobal.IIntegracionSAPService")]
    public interface IIntegracionSAPService {
        
        // CODEGEN: Parameter 'EmitirCFDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmitirCFD", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmitirCFDRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(Facturacion.BLL.PegasoGlobal.WCFServiceFault), Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmitirCFDWCFSer" +
            "viceFaultFault", Name="WCFServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.BLL.PegasoGlobal.EmitirCFDResponse EmitirCFD(Facturacion.BLL.PegasoGlobal.EmitirCFDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmitirCFD", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmitirCFDRespon" +
            "se")]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.EmitirCFDResponse> EmitirCFDAsync(Facturacion.BLL.PegasoGlobal.EmitirCFDRequest request);
        
        // CODEGEN: Parameter 'ModificarAddendaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/ModificarAddend" +
            "a", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/ModificarAddend" +
            "aResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Facturacion.BLL.PegasoGlobal.WCFServiceFault), Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/ModificarAddend" +
            "aWCFServiceFaultFault", Name="WCFServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.BLL.PegasoGlobal.ModificarAddendaResponse ModificarAddenda(Facturacion.BLL.PegasoGlobal.ModificarAddendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/ModificarAddend" +
            "a", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/ModificarAddend" +
            "aResponse")]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.ModificarAddendaResponse> ModificarAddendaAsync(Facturacion.BLL.PegasoGlobal.ModificarAddendaRequest request);
        
        // CODEGEN: Parameter 'CancelarCFDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelarCFD", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelarCFDResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Facturacion.BLL.PegasoGlobal.WCFServiceFault), Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelarCFDWCFS" +
            "erviceFaultFault", Name="WCFServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.BLL.PegasoGlobal.CancelarCFDResponse CancelarCFD(Facturacion.BLL.PegasoGlobal.CancelarCFDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelarCFD", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelarCFDResp" +
            "onse")]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.CancelarCFDResponse> CancelarCFDAsync(Facturacion.BLL.PegasoGlobal.CancelarCFDRequest request);
        
        // CODEGEN: Generating message contract since the operation EmisionRapidaCFD is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "D", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "DResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Facturacion.BLL.PegasoGlobal.WCFServiceFault), Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "DWCFServiceFaultFault", Name="WCFServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.BLL.PegasoGlobal.RespuestaEmisionXml1 EmisionRapidaCFD(Facturacion.BLL.PegasoGlobal.PeticionEmisionXml request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "D", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "DResponse")]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.RespuestaEmisionXml1> EmisionRapidaCFDAsync(Facturacion.BLL.PegasoGlobal.PeticionEmisionXml request);
        
        // CODEGEN: Parameter 'EmisionRapidaCFDXmlResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "DXml", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "DXmlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Facturacion.BLL.PegasoGlobal.WCFServiceFault), Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "DXmlWCFServiceFaultFault", Name="WCFServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlResponse EmisionRapidaCFDXml(Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "DXml", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/EmisionRapidaCF" +
            "DXmlResponse")]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlResponse> EmisionRapidaCFDXmlAsync(Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlRequest request);
        
        // CODEGEN: Parameter 'CancelaCFDPorSolicitudResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelaCFDPorSo" +
            "licitud", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelaCFDPorSo" +
            "licitudResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Facturacion.BLL.PegasoGlobal.WCFServiceFault), Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelaCFDPorSo" +
            "licitudWCFServiceFaultFault", Name="WCFServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudResponse CancelaCFDPorSolicitud(Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelaCFDPorSo" +
            "licitud", ReplyAction="http://namespace.pegasotecnologia.com/SCFD/IIntegracionSAPService/CancelaCFDPorSo" +
            "licitudResponse")]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudResponse> CancelaCFDPorSolicitudAsync(Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmitirCFD", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class EmitirCFDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement xml;
        
        public EmitirCFDRequest() {
        }
        
        public EmitirCFDRequest(System.Xml.XmlElement xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmitirCFDResponse", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class EmitirCFDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement EmitirCFDResult;
        
        public EmitirCFDResponse() {
        }
        
        public EmitirCFDResponse(System.Xml.XmlElement EmitirCFDResult) {
            this.EmitirCFDResult = EmitirCFDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModificarAddenda", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class ModificarAddendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement xml;
        
        public ModificarAddendaRequest() {
        }
        
        public ModificarAddendaRequest(System.Xml.XmlElement xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModificarAddendaResponse", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class ModificarAddendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement ModificarAddendaResult;
        
        public ModificarAddendaResponse() {
        }
        
        public ModificarAddendaResponse(System.Xml.XmlElement ModificarAddendaResult) {
            this.ModificarAddendaResult = ModificarAddendaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarCFD", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class CancelarCFDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement xml;
        
        public CancelarCFDRequest() {
        }
        
        public CancelarCFDRequest(System.Xml.XmlElement xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarCFDResponse", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class CancelarCFDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement CancelarCFDResult;
        
        public CancelarCFDResponse() {
        }
        
        public CancelarCFDResponse(System.Xml.XmlElement CancelarCFDResult) {
            this.CancelarCFDResult = CancelarCFDResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Pegaso.SCFD.Comun.Comunes.Mensajes")]
    public partial class Metadato : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://namespace.pegasotecnologia.com/SCFD")]
    public partial class RespuestaEmisionXml : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error[] erroresField;
        
        private System.Xml.XmlElement documentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public Error[] Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
                this.RaisePropertyChanged("Errores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Xml.XmlElement Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string categoriaField;
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("Categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PeticionEmisionXml {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD")]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Pegaso.SCFD.Comun.Comunes.Mensajes")]
        public Facturacion.BLL.PegasoGlobal.Metadato[] Metadatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement Documento;
        
        public PeticionEmisionXml() {
        }
        
        public PeticionEmisionXml(Facturacion.BLL.PegasoGlobal.Metadato[] Metadatos, System.Xml.XmlElement Documento) {
            this.Metadatos = Metadatos;
            this.Documento = Documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RespuestaEmisionXml1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD")]
        public bool Exito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        public Facturacion.BLL.PegasoGlobal.RespuestaEmisionXml RespuestaEmisionXml;
        
        public RespuestaEmisionXml1() {
        }
        
        public RespuestaEmisionXml1(bool Exito, Facturacion.BLL.PegasoGlobal.RespuestaEmisionXml RespuestaEmisionXml) {
            this.Exito = Exito;
            this.RespuestaEmisionXml = RespuestaEmisionXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmisionRapidaCFDXml", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class EmisionRapidaCFDXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement peticion;
        
        public EmisionRapidaCFDXmlRequest() {
        }
        
        public EmisionRapidaCFDXmlRequest(System.Xml.XmlElement peticion) {
            this.peticion = peticion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmisionRapidaCFDXmlResponse", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class EmisionRapidaCFDXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement EmisionRapidaCFDXmlResult;
        
        public EmisionRapidaCFDXmlResponse() {
        }
        
        public EmisionRapidaCFDXmlResponse(System.Xml.XmlElement EmisionRapidaCFDXmlResult) {
            this.EmisionRapidaCFDXmlResult = EmisionRapidaCFDXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelaCFDPorSolicitud", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class CancelaCFDPorSolicitudRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement peticion;
        
        public CancelaCFDPorSolicitudRequest() {
        }
        
        public CancelaCFDPorSolicitudRequest(System.Xml.XmlElement peticion) {
            this.peticion = peticion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelaCFDPorSolicitudResponse", WrapperNamespace="http://namespace.pegasotecnologia.com/SCFD", IsWrapped=true)]
    public partial class CancelaCFDPorSolicitudResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://namespace.pegasotecnologia.com/SCFD", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement CancelaCFDPorSolicitudResult;
        
        public CancelaCFDPorSolicitudResponse() {
        }
        
        public CancelaCFDPorSolicitudResponse(System.Xml.XmlElement CancelaCFDPorSolicitudResult) {
            this.CancelaCFDPorSolicitudResult = CancelaCFDPorSolicitudResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegracionSAPServiceChannel : Facturacion.BLL.PegasoGlobal.IIntegracionSAPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegracionSAPServiceClient : System.ServiceModel.ClientBase<Facturacion.BLL.PegasoGlobal.IIntegracionSAPService>, Facturacion.BLL.PegasoGlobal.IIntegracionSAPService {
        
        public IntegracionSAPServiceClient() {
        }
        
        public IntegracionSAPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegracionSAPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracionSAPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracionSAPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Facturacion.BLL.PegasoGlobal.EmitirCFDResponse Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.EmitirCFD(Facturacion.BLL.PegasoGlobal.EmitirCFDRequest request) {
            return base.Channel.EmitirCFD(request);
        }
        
        public System.Xml.XmlElement EmitirCFD(System.Xml.XmlElement xml) {
            Facturacion.BLL.PegasoGlobal.EmitirCFDRequest inValue = new Facturacion.BLL.PegasoGlobal.EmitirCFDRequest();
            inValue.xml = xml;
            Facturacion.BLL.PegasoGlobal.EmitirCFDResponse retVal = ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).EmitirCFD(inValue);
            return retVal.EmitirCFDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.EmitirCFDResponse> Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.EmitirCFDAsync(Facturacion.BLL.PegasoGlobal.EmitirCFDRequest request) {
            return base.Channel.EmitirCFDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.EmitirCFDResponse> EmitirCFDAsync(System.Xml.XmlElement xml) {
            Facturacion.BLL.PegasoGlobal.EmitirCFDRequest inValue = new Facturacion.BLL.PegasoGlobal.EmitirCFDRequest();
            inValue.xml = xml;
            return ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).EmitirCFDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Facturacion.BLL.PegasoGlobal.ModificarAddendaResponse Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.ModificarAddenda(Facturacion.BLL.PegasoGlobal.ModificarAddendaRequest request) {
            return base.Channel.ModificarAddenda(request);
        }
        
        public System.Xml.XmlElement ModificarAddenda(System.Xml.XmlElement xml) {
            Facturacion.BLL.PegasoGlobal.ModificarAddendaRequest inValue = new Facturacion.BLL.PegasoGlobal.ModificarAddendaRequest();
            inValue.xml = xml;
            Facturacion.BLL.PegasoGlobal.ModificarAddendaResponse retVal = ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).ModificarAddenda(inValue);
            return retVal.ModificarAddendaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.ModificarAddendaResponse> Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.ModificarAddendaAsync(Facturacion.BLL.PegasoGlobal.ModificarAddendaRequest request) {
            return base.Channel.ModificarAddendaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.ModificarAddendaResponse> ModificarAddendaAsync(System.Xml.XmlElement xml) {
            Facturacion.BLL.PegasoGlobal.ModificarAddendaRequest inValue = new Facturacion.BLL.PegasoGlobal.ModificarAddendaRequest();
            inValue.xml = xml;
            return ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).ModificarAddendaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Facturacion.BLL.PegasoGlobal.CancelarCFDResponse Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.CancelarCFD(Facturacion.BLL.PegasoGlobal.CancelarCFDRequest request) {
            return base.Channel.CancelarCFD(request);
        }
        
        public System.Xml.XmlElement CancelarCFD(System.Xml.XmlElement xml) {
            Facturacion.BLL.PegasoGlobal.CancelarCFDRequest inValue = new Facturacion.BLL.PegasoGlobal.CancelarCFDRequest();
            inValue.xml = xml;
            Facturacion.BLL.PegasoGlobal.CancelarCFDResponse retVal = ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).CancelarCFD(inValue);
            return retVal.CancelarCFDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.CancelarCFDResponse> Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.CancelarCFDAsync(Facturacion.BLL.PegasoGlobal.CancelarCFDRequest request) {
            return base.Channel.CancelarCFDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.CancelarCFDResponse> CancelarCFDAsync(System.Xml.XmlElement xml) {
            Facturacion.BLL.PegasoGlobal.CancelarCFDRequest inValue = new Facturacion.BLL.PegasoGlobal.CancelarCFDRequest();
            inValue.xml = xml;
            return ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).CancelarCFDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Facturacion.BLL.PegasoGlobal.RespuestaEmisionXml1 Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.EmisionRapidaCFD(Facturacion.BLL.PegasoGlobal.PeticionEmisionXml request) {
            return base.Channel.EmisionRapidaCFD(request);
        }
        
        public bool EmisionRapidaCFD(Facturacion.BLL.PegasoGlobal.Metadato[] Metadatos, System.Xml.XmlElement Documento, out Facturacion.BLL.PegasoGlobal.RespuestaEmisionXml RespuestaEmisionXml) {
            Facturacion.BLL.PegasoGlobal.PeticionEmisionXml inValue = new Facturacion.BLL.PegasoGlobal.PeticionEmisionXml();
            inValue.Metadatos = Metadatos;
            inValue.Documento = Documento;
            Facturacion.BLL.PegasoGlobal.RespuestaEmisionXml1 retVal = ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).EmisionRapidaCFD(inValue);
            RespuestaEmisionXml = retVal.RespuestaEmisionXml;
            return retVal.Exito;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.RespuestaEmisionXml1> Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.EmisionRapidaCFDAsync(Facturacion.BLL.PegasoGlobal.PeticionEmisionXml request) {
            return base.Channel.EmisionRapidaCFDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.RespuestaEmisionXml1> EmisionRapidaCFDAsync(Facturacion.BLL.PegasoGlobal.Metadato[] Metadatos, System.Xml.XmlElement Documento) {
            Facturacion.BLL.PegasoGlobal.PeticionEmisionXml inValue = new Facturacion.BLL.PegasoGlobal.PeticionEmisionXml();
            inValue.Metadatos = Metadatos;
            inValue.Documento = Documento;
            return ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).EmisionRapidaCFDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlResponse Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.EmisionRapidaCFDXml(Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlRequest request) {
            return base.Channel.EmisionRapidaCFDXml(request);
        }
        
        public System.Xml.XmlElement EmisionRapidaCFDXml(System.Xml.XmlElement peticion) {
            Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlRequest inValue = new Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlRequest();
            inValue.peticion = peticion;
            Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlResponse retVal = ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).EmisionRapidaCFDXml(inValue);
            return retVal.EmisionRapidaCFDXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlResponse> Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.EmisionRapidaCFDXmlAsync(Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlRequest request) {
            return base.Channel.EmisionRapidaCFDXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlResponse> EmisionRapidaCFDXmlAsync(System.Xml.XmlElement peticion) {
            Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlRequest inValue = new Facturacion.BLL.PegasoGlobal.EmisionRapidaCFDXmlRequest();
            inValue.peticion = peticion;
            return ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).EmisionRapidaCFDXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudResponse Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.CancelaCFDPorSolicitud(Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudRequest request) {
            return base.Channel.CancelaCFDPorSolicitud(request);
        }
        
        public System.Xml.XmlElement CancelaCFDPorSolicitud(System.Xml.XmlElement peticion) {
            Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudRequest inValue = new Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudRequest();
            inValue.peticion = peticion;
            Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudResponse retVal = ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).CancelaCFDPorSolicitud(inValue);
            return retVal.CancelaCFDPorSolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudResponse> Facturacion.BLL.PegasoGlobal.IIntegracionSAPService.CancelaCFDPorSolicitudAsync(Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudRequest request) {
            return base.Channel.CancelaCFDPorSolicitudAsync(request);
        }
        
        public System.Threading.Tasks.Task<Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudResponse> CancelaCFDPorSolicitudAsync(System.Xml.XmlElement peticion) {
            Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudRequest inValue = new Facturacion.BLL.PegasoGlobal.CancelaCFDPorSolicitudRequest();
            inValue.peticion = peticion;
            return ((Facturacion.BLL.PegasoGlobal.IIntegracionSAPService)(this)).CancelaCFDPorSolicitudAsync(inValue);
        }
    }
}
